language: node_js
node_js:
  - 8.5.5
cache: npm

before_install:
  - npm i -g npm@8.5.5

install:
  - npm install

script:
  - make test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages