version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
    steps:
      - checkout
      - run:
          name: Install and Make
          command: npm install && make test-coverage
      - coveralls/upload
