version: 2.1
orbs:
  coveralls: coveralls/coveralls@x.y.z
jobs:
  build-1:
    docker:
      - image: 'circleci/node:10.0.0'
    steps:
      - checkout
      - run:
          name: Install and Make 1
          command: npm install && make test-coverage-1
      - coveralls/upload:
          parallel: true
          flag_name: Test 1
  build-2:
    docker:
      - image: 'circleci/node:10.0.0'
    steps:
      - checkout
      - run:
          name: Install and Make 2
          command: npm install && make test-coverage-2
      - coveralls/upload:
          parallel: true
          flag_name: Test 2
  done:
    docker:
      - image: 'circleci/node:10.0.0'
    steps:
      - coveralls/upload:
          parallel_finished: true
workflows:
  test_parallel_then_upload:
    jobs:
      - build-1
      - build-2
      - done:
          requires:
            - build-1
            - build-2
